### ISSUE TITLE
BatchRun: support GET APIs

### ISSUE THREAD

**Issue by gkzz** [Magic-Pod/magicpod-api-client#7]
### Describe our problem
We have no ways to call, with **`magicpod-api-client`** , GET the following BatchRun APIs;
- `/v1.0/{organization_name}/{project_name}/batch-run/{batch_run_number}/`
- `/v1.0/{organization_name}/{project_name}/batch-runs/`

src: https://magic-pod.com/api/v1.0/doc/

The only way to get the BatchRun's results is to call the APIs directory with curl command, or something :(

### Proposed Solution
- All we have to do in order to get BatchRun's results and the test-cases' results is to execute it only once.
  - Once we execute it, **`magicpod-api-client`** calls `/v1.0/{organization_name}/{project_name}/batch-runs/` API and `/v1.0/{organization_name}/{project_name}/batch-run/{batch_run_number}/` APIs repeatedly for number of `{batch_run_number}` s.

### Clues to solve the problem
- We've already have the functions to call these APIs 
  - `/v1.0/{organization_name}/{project_name}/batch-run/{batch_run_number}/`
    - https://github.com/Magic-Pod/magicpod-api-client/blob/9bf6921be6e742ff93b271ad98a68287fbd53a9a/common/common.go#L180-L187
  -  `/v1.0/{organization_name}/{project_name}/batch-runs/`
      - https://github.com/Magic-Pod/magicpod-api-client/blob/9bf6921be6e742ff93b271ad98a68287fbd53a9a/common/common.go#L197-L201
- These functions are inner ones
  - https://github.com/Magic-Pod/magicpod-api-client/blob/9bf6921be6e742ff93b271ad98a68287fbd53a9a/magicpod-api-client.go#L136-L143
  - https://github.com/Magic-Pod/magicpod-api-client/blob/9bf6921be6e742ff93b271ad98a68287fbd53a9a/magicpod-api-client.go#L271-L282

**Comment by yaumu3** [comment]
Thank you for informative suggestion! As for `/v1.0/{organization_name}/{project_name}/batch-run/{batch_run_number}/`, it seems that utilizing `GetBatchRun` is the key. I'm trying to partially resolve it with #8.

**Comment by gkzz** [comment]
Thx always :)
I'll re-open one, when I'm faced with problems.

**Comment by nkns165** [comment]
Sorry, we've not yet supported `/v1.0/{organization_name}/{project_name}/batch-runs/`.
Let me reopen now.
